### ISSUE TITLE
Unable to install via npm

### ISSUE THREAD

**Issue by GildedHonour** [purescript/documentation#167]
I'm trying to install it:
```

    $ sudo npm install -g purescript
    /usr/bin/purs -> /usr/lib/node_modules/purescript/purs.bin

    > purescript@0.11.7 postinstall /usr/lib/node_modules/purescript
    > install-purescript --purs-ver=0.11.7 --name=purs.bin .

    TypeError: Cannot read property 'setEncoding' of undefined
        at spawnStack (/usr/lib/node_modules/purescript/node_modules/spawn-stack/index.js:51:13)
        at observer (/usr/lib/node_modules/purescript/node_modules/download-or-build-purescript/index.js:162:7)
        at new Subscription (/usr/lib/node_modules/purescript/node_modules/zen-observable/zen-observable.js:103:32)
        at Observable.subscribe (/usr/lib/node_modules/purescript/node_modules/zen-observable/zen-observable.js:229:12)
        at observer (/usr/lib/node_modules/purescript/node_modules/install-purescript/index.js:101:52)
        at new Subscription (/usr/lib/node_modules/purescript/node_modules/zen-observable/zen-observable.js:103:32)
        at Observable.subscribe (/usr/lib/node_modules/purescript/node_modules/zen-observable/zen-observable.js:229:12)
        at Object.<anonymous> (/usr/lib/node_modules/purescript/node_modules/install-purescript-cli/index.js:419:4)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! purescript@0.11.7 postinstall: `install-purescript --purs-ver=0.11.7 --name=purs.bin .`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the purescript@0.11.7 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2018-03-09T12_21_49_226Z-debug.log


```
And
```

      $ /root/.npm/_logs/2018-03-09T12_21_49_226Z-debug.log
      [..........................................]
      3580 verbose lifecycle purescript@0.11.7~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/purescript/node_modules/.bin:/usr/lib/node_modules/.bin:/home/alex/.gem/ruby/2.5.0/bin:/home/alex/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/bin:/home/alex/.rubies/ruby-2.5.0/bin:/bin:/usr/bin:/usr/bin:/usr/ucb:/usr/local/sbin:/usr/local/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/atlassian/plugin-sdk/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
      3581 verbose lifecycle purescript@0.11.7~postinstall: CWD: /usr/lib/node_modules/purescript
      3582 silly lifecycle purescript@0.11.7~postinstall: Args: [ '-c',
      3582 silly lifecycle   'install-purescript --purs-ver=0.11.7 --name=purs.bin .' ]
      3583 silly lifecycle purescript@0.11.7~postinstall: Returned: code: 1  signal: null
      3584 info lifecycle purescript@0.11.7~postinstall: Failed to exec postinstall script
      3585 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
      3586 verbose stack Error: purescript@0.11.7 postinstall: `install-purescript --purs-ver=0.11.7 --name=purs.bin .`
      3586 verbose stack Exit status 1
      3586 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
      3586 verbose stack     at EventEmitter.emit (events.js:127:13)
      3586 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
      3586 verbose stack     at ChildProcess.emit (events.js:127:13)
      3586 verbose stack     at maybeClose (internal/child_process.js:933:16)
      3586 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
      3587 verbose pkgid purescript@0.11.7
      3588 verbose cwd /home/alex/projects/companies/juspay/halogen-dom
      3589 verbose Linux 4.14.21-1-lts
      3590 verbose argv "/usr/bin/node" "/bin/npm" "install" "-g" "purescript"
      3591 verbose node v9.6.1
      3592 verbose npm  v5.7.1
      3593 error code ELIFECYCLE
      3594 error errno 1
      3595 error purescript@0.11.7 postinstall: `install-purescript --purs-ver=0.11.7 --name=purs.bin .`
      3595 error Exit status 1
      3596 error Failed at the purescript@0.11.7 postinstall script.
      3596 error This is probably not a problem with npm. There is likely additional logging output above.
      3597 verbose exit [ 1, true ]

```

Why is this?

Without "sudo" npm install -g purescript fails due to "access denied."

**Comment by garyb** [comment]
I imagine this is perhaps due to an older node version or something, given it's complaining about a missing function. 

Could you re-open on https://github.com/purescript-contrib/node-purescript if upgrading node doesn't fix it? This repo is for the compiler rather than the node wrapper.
