### ISSUE TITLE
npm install -g purescript  fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mseshachalam** [purescript/documentation#254]
```
/home/seshachalamm/.nvm/versions/node/v8.15.1/bin/purs -> /home/seshachalamm/.nvm/versions/node/v8.15.1/lib/node_modules/purescript/purs.bin

> purescript@0.13.0 postinstall /home/seshachalamm/.nvm/versions/node/v8.15.1/lib/node_modules/purescript
> install-purescript --purs-ver=0.13.0

/home/seshachalamm/.nvm/versions/node/v8.15.1/lib/node_modules/purescript/node_modules/install-purescript-cli/index.js:97
	} catch {
	        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by justinwoo** [comment]
This is the same issue as https://github.com/purescript/purescript/issues/3677, you should upgrade Node to >10

**Comment by hdgarrood** [comment]
^ yep. See also https://github.com/purescript/npm-installer/issues/2 and https://github.com/purescript/npm-installer/issues/9. Thanks anyway for the report!

**Comment by garyb** [comment]
Maybe we should pin an issue in here until we release 0.13.1?

**Comment by hdgarrood** [comment]
Yes, that sounds like a good plan.

**Comment by mseshachalam** [comment]
May be update the docs
